### ISSUE TITLE
Problem when changing categories for multiple records

### ISSUE THREAD

**Issue by MagefanCustomer** [magefan/magento-2-extended-product-grid#2]
Using the plugin from MageFan Extended Product Grid, there is a problem when changing categories for multiple records.

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'led-napajalnik-pretvornik-adapter-mean-well-100w-8-5a-ip20-ac...' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID', query was: INSERT INTO `url_rewrite` (`redirect_type`,`is_autogenerated`,`metadata`,`description`,`entity_type`,`entity_id`,`request_path`,`target_path`,`store_id`) VALUES`

**Comment by magefan** [comment]
Thank you for your report.

The issue most likely **appears because you have 2 products with the same name (url_path) and try to add them to one category**. If the products with the same name are added to different categories, they have different paths, so it's fine and no issues appear.
 
So, please check if you have the products with the same name and try to avoid adding them to the same category when using our [Magento 2 Extended Product Grid](**url**) Extension.
